Repository felipeangelimvieira/prophetverse, pull requests merged in 2024-07, with the labels that each got.

#72 [MNT] Lint and split effects module
  .pre-commit-config.yaml
  docs/examples/count-data.ipynb
  docs/examples/custom-trend.ipynb
  docs/examples/hierarchical.ipynb
  docs/examples/univariate.ipynb
  src/prophetverse/effects.py
  src/prophetverse/effects/base.py
  src/prophetverse/effects/effect_apply.py
  src/prophetverse/effects/hill.py
  src/prophetverse/effects/linear.py
  src/prophetverse/effects/log.py
  src/prophetverse/models.py
  src/prophetverse/sktime/base.py
  src/prophetverse/utils/algebric_operations.py
  tests/conftest.py
  tests/effects/__init__.py
  tests/effects/test_base.py
  tests/effects/test_effects.py
  tests/effects/test_effects_apply.py
  tests/effects/test_hill.py
  tests/effects/test_linear.py
  tests/effects/test_log.py
  tests/sktime/_utils.py
  tests/sktime/test_multivariate.py
  tests/sktime/test_univariate.py
Labels: maintenance

#77 [FIX] Suggested capacity value when y is not scaled
  src/prophetverse/trend/piecewise.py
Labels: bug

#78 [MNT] Add __init__ to effects
  src/prophetverse/effects/__init__.py
  src/prophetverse/effects/base.py
  src/prophetverse/effects/effect_apply.py
  src/prophetverse/effects/hill.py
  src/prophetverse/effects/linear.py
  src/prophetverse/effects/log.py
Labels: maintenance

#82 [MNT] Use pip instead of poetry in CI
  .github/workflows/ci.yaml
  pyproject.toml
Labels: maintenance

#83 [DOC] Use katex for math equations and add Prophetverse class to references
  docs/examples/custom-trend.ipynb
  docs/javascripts/katex.js
  docs/javascripts/mathjax.js
  docs/reference/sktime/prophetverse.md
  mkdocs.yml
  src/prophetverse/sktime/univariate.py
Labels: documentation

#87 [DOC] Add versioning to mkdocs
  mkdocs.yml
Labels: documentation

#88 [FIX] Raise MAPInferenceEngineError if loss is nan
  src/prophetverse/engine.py
  tests/test_engine.py
Labels: bug

#92 [MNT] Update BaseEffect docstrings
  docs/README.md
  src/prophetverse/effects/base.py
  tests/effects/test_base.py
Labels: documentation

#93 [MNT] Add deprecation warnings
  pyproject.toml
  src/prophetverse/effects/base.py
  src/prophetverse/sktime/univariate.py
Labels: maintenance

#95 [ENH] Trend as an Effect
  .gitignore
  docs/deprecation.md
  extension_templates/effect.py
  src/prophetverse/effects/base.py
  src/prophetverse/effects/fourier.py
  src/prophetverse/effects/hill.py
  src/prophetverse/effects/lift_experiment.py
  src/prophetverse/effects/linear.py
  src/prophetverse/effects/log.py
  src/prophetverse/effects/trend/__init__.py
  src/prophetverse/effects/trend/base.py
  src/prophetverse/effects/trend/flat.py
  src/prophetverse/effects/trend/piecewise.py
  src/prophetverse/models.py
  src/prophetverse/sktime/base.py
  src/prophetverse/sktime/multivariate.py
  src/prophetverse/sktime/univariate.py
  src/prophetverse/trend/__init__.py
  src/prophetverse/trend/base.py
  src/prophetverse/utils/multiindex.py
  tests/conftest.py
  tests/effects/test_base.py
  tests/effects/test_fourier.py
  tests/effects/test_hill.py
  tests/effects/test_lift_experiment.py
  tests/effects/test_linear.py
  tests/effects/test_log.py
  tests/models/multivariate_model/test_frame_to_array.py
  tests/sktime/test_base.py
  tests/sktime/test_univariate.py
  tests/trend/test_flat.py
  tests/trend/test_piecewise.py
Labels: enhancement

#97 [DOC] Update docs to describe 0.4.0 API
  .gitignore
  .pre-commit-config.yaml
  docs/README.md
  docs/deprecation.md
  docs/effects-api.md
  docs/examples/count-data.ipynb
  docs/examples/custom-effect.ipynb
  docs/examples/custom-trend.ipynb
  docs/examples/hierarchical.ipynb
  docs/examples/univariate.ipynb
  docs/getting-started.md
  docs/javascripts/katex.js
  docs/javascripts/mathjax.js
  docs/static/prophetverse-universe.png
  docs/stylesheets/extra.css
  docs/the-theory.md
  mkdocs.yml
  pyproject.toml
  src/prophetverse/effects/base.py
  src/prophetverse/effects/trend/piecewise.py
Labels: documentation

#98 [DOC] Hyperlinks, fix poetry dev installation tutorial
  docs/development/development-guide.md
  docs/effects-api.md
  docs/examples/univariate.ipynb
  docs/the-theory.md
Labels: documentation

#100 [DOC] Update README.md
  README.md
Labels: documentation
