Repository felipeangelimvieira/prophetverse, pull requests merged in 2024-06, with the labels that each got.

#56 [Resolves #54] Add pre-commit and contributing guidelines
  .pre-commit-config.yaml
  README.md
  docs/development/development-guide.md
  mkdocs.yml
  poetry.lock
  pyproject.toml
Labels: documentation

#58 [ENH] New predict functions, and docs on custom trend
  .gitignore
  docs/examples/custom-trend.ipynb
  docs/examples/tensorflow_tensorflow-stars-history.csv
  mkdocs.yml
  poetry.lock
  pyproject.toml
  src/prophetverse/effects.py
  src/prophetverse/engine.py
  src/prophetverse/models.py
  src/prophetverse/sktime/base.py
  src/prophetverse/sktime/multivariate.py
  src/prophetverse/sktime/univariate.py
  tests/conftest.py
  tests/effects/test_effects.py
  tests/sktime/_utils.py
  tests/sktime/test_multivariate.py
  tests/sktime/test_sktime_check_estimator.py
  tests/sktime/test_univariate.py
Labels: enhancement

#62 [MNT] Simplify tests
  .github/workflows/ci.yaml
  docs/development/development-guide.md
  pyproject.toml
  tests/conftest.py
  tests/sktime/test_multivariate.py
  tests/sktime/test_univariate.py
Labels: maintenance

#65 [STYLE] pre-commit update #64
  .pre-commit-config.yaml
Labels: maintenance

#66 [MNT] Fix pre-commit
  .pre-commit-config.yaml
Labels: maintenance

#68 [ENH] Add Prophetverse class and make BaseBayesianForecaster handle scaling based on discrete/continuous likelihood
  docs/examples/count-data.ipynb
  docs/examples/custom-trend.ipynb
  docs/examples/hierarchical.ipynb
  docs/examples/univariate.ipynb
  src/prophetverse/models.py
  src/prophetverse/sktime/base.py
  src/prophetverse/sktime/univariate.py
  src/prophetverse/trend/piecewise.py
  tests/sktime/_utils.py
  tests/sktime/test_sktime_check_estimator.py
  tests/sktime/test_univariate.py
  tests/trend/test_piecewise.py
Labels: enhancement

#74 [MNT] Lint and fix docstring in sktime and trend modules
  src/prophetverse/distributions.py
  src/prophetverse/engine.py
  src/prophetverse/models.py
  src/prophetverse/sktime/__init__.py
  src/prophetverse/sktime/_expand_column_per_level.py
  src/prophetverse/sktime/base.py
  src/prophetverse/sktime/multivariate.py
  src/prophetverse/sktime/seasonality.py
  src/prophetverse/sktime/univariate.py
  src/prophetverse/trend/__init__.py
  src/prophetverse/trend/flat.py
  src/prophetverse/trend/piecewise.py
  src/prophetverse/utils/__init__.py
  src/prophetverse/utils/frame_to_array.py
  src/prophetverse/utils/multiindex.py
  src/prophetverse/utils/regex.py
  tests/models/multivariate_model/test_frame_to_array.py
  tests/sktime/test_univariate.py
  tests/sktime/test_utils.py
Labels: maintenance

#76 [DOC] Change mkdocs config to use numpy style docstrings
  mkdocs.yml
  pyproject.toml
Labels: documentation
