Repository felipeangelimvieira/prophetverse, pull requests merged in 2025-03, with the labels that each got.

#179 [ENH] Take the number of chains into account in MCMCInferenceEngine._predict
  src/prophetverse/engine/mcmc.py
Labels: enhancement

#184 [ENH] Use property decorator for posterior samples
  src/prophetverse/sktime/base.py
  tests/sktime/test_base.py
Labels: enhancement

#188 [MNT] Abort if new PR is detected
  .github/workflows/ci.yaml
Labels: maintenance

#186 [DOC] Remove input feature column names from docs
  README.md
  docs/README.md
  docs/effects-api.md
  docs/examples/count-data.ipynb
  docs/examples/custom-effect.ipynb
  docs/examples/custom-trend.ipynb
  docs/examples/hierarchical.ipynb
  docs/examples/tensorflow_tensorflow-stars-history.csv
  docs/examples/tourism.csv
  docs/examples/univariate.ipynb
  docs/howto/composite-exogenous-effects/index.ipy
  docs/howto/composite-exogenous-effects/index.md
  docs/howto/custom-trend/__index.ipy
  docs/howto/custom-trend/index.ipy
  docs/howto/index.md
  docs/static/avatar-removebg.png
  docs/static/avatar.webp
  docs/static/favicon.ico
  docs/static/logo-removebg.png
  docs/static/logotext-removebg.png
  docs/static/prophetverse-logo.png
  docs/stylesheets/extra.css
  mkdocs.yml
  src/prophetverse/effects/base.py
  src/prophetverse/effects/exact_likelihood.py
  src/prophetverse/effects/lift_likelihood.py
  src/prophetverse/sktime/multivariate.py
Labels: documentation

#183 [FIX] Cast X to inner mtype in custom public methods
  src/prophetverse/sktime/base.py
  tests/engine/test_utils.py
  tests/experimental/test_simulate.py
Labels: bug
